### ISSUE TITLE
running example

### ISSUE THREAD

**Issue by chenweigu** [Icheler/TU_Much_Exploration#1]
Do you have a full running example? After the configuration, I ran the launch file and found that many parameters seemed to be missing.

**Comment by Icheler** [comment]
Can you please provide more information about the issue, like the error message, system information, which ROS and os you use for example?

Then we can more easily pinpoint the problem.

**Comment by chenweigu** [comment]
Thank you for your reply! 
After installing the dependencies according to “install_script.bash“, I put co-explore under the same "catkin_ws/src" and it compiled successfully, but after I ran "roslaunch tme_startup complete_launch.launch " :

... logging to /home/wgchen/.ros/log/b570bf22-f95a-11ed-bd46-57d25674f991/roslaunch-wgchen-5716.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

xacro: in-order processing became default in ROS Melodic. You can drop the option.
xacro: in-order processing became default in ROS Melodic. You can drop the option.
RLException: environment variable 'tme_start_robot1_x' is not set
The traceback for the exception was written to the log file

Seems to be missing a lot of configuration parameters, is there something wrong with my configuration?  or is there a complete tutorial case. thanks!

**Comment by chenweigu** [comment]
> Can you please provide more information about the issue, like the error message, system information, which ROS and os you use for example?
> 
> Then we can more easily pinpoint the problem.

Thank you for your reply! 
After installing the dependencies according to “install_script.bash“, I put co-explore under the same "catkin_ws/src" and it compiled successfully, but after I ran "roslaunch tme_startup complete_launch.launch " :

... logging to /home/wgchen/.ros/log/b570bf22-f95a-11ed-bd46-57d25674f991/roslaunch-wgchen-5716.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

xacro: in-order processing became default in ROS Melodic. You can drop the option.
xacro: in-order processing became default in ROS Melodic. You can drop the option.
RLException: environment variable 'tme_start_robot1_x' is not set
The traceback for the exception was written to the log file

Seems to be missing a lot of configuration parameters, is there something wrong with my configuration?  or is there a complete tutorial case. thanks!

**Comment by chenweigu** [comment]
> Can you please provide more information about the issue, like the error message, system information, which ROS and os you use for example?
> 
> Then we can more easily pinpoint the problem.

Thank you for your reply! 
After installing the dependencies according to “install_script.bash“, I put co-explore under the same "catkin_ws/src" and it compiled successfully, 

wgchen@wgchen:~/ws/catkin_ws/src/coExplore-main$ source config_script.bash 
-------------------------------------------------------------
coExplore configuration
-------------------------------------------------------------
tme_ROBOT_ENV: [marty, v2_maze, map_3]
tme_start_num: [2 - 5]
tme_expl_method: [nearest, minPos, nextFrontier, coExplore, co122]
tme_stop_time: number in seconds the simluation should run
-------------------------------------------------------------
selected world is: map_3
starting num of robots 5: [2: True, 3: True, 4: True, 5: True] 
chosen method is: coExplore
chosen stop time is: 300
-------------------------------------------------------------
wgchen@wgchen:~/ws/catkin_ws/src/coExplore-main$ cd ../..
wgchen@wgchen:~/ws/catkin_ws$ source ./devel/setup.bash 
wgchen@wgchen:~/ws/catkin_ws$ roslaunch tme_startup complete_launch.launch

Then some errors appear. 

process[tme_frontier_search-39]: started with pid [7369]
INFO: cannot create a symlink to latest log directory: [Errno 17] File exists: '/home/wgchen/.ros/log/85118e44-f95d-11ed-bd46-57d25674f991' -> '/home/wgchen/.ros/log/latest'
process[tme_frontier_assign-40]: started with pid [7372]
process[tme_map_compare-41]: started with pid [7381]
[ INFO] [1684841559.443016737]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1684841559.443893426]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1684841559.710251326, 10.499000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1684841559.725833965, 10.514000000]: Physics dynamic reconfigure ready.
../src/intel/isl/isl.c:2105: FINISHME: ../src/intel/isl/isl.c:isl_surf_supports_ccs: CCS for 3D textures is disabled, but a workaround is available.
Traceback (most recent call last):
  File "/home/wgchen/ws/catkin_ws/devel/lib/tme_exploration/frontier_assign", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/home/wgchen/ws/catkin_ws/src/coExplore-main/tme_exploration/src/frontier_assign", line 16, in <module>
    from skimage import graph
ModuleNotFoundError: No module named 'skimage'
================================================================================REQUIRED process [tme_frontier_assign-40] has died!
process has died [pid 7372, exit code 1, cmd bash -c sleep 1.0; $0 $@ /home/wgchen/ws/catkin_ws/devel/lib/tme_exploration/frontier_assign __name:=tme_frontier_assign __log:=/home/wgchen/.ros/log/85118e44-f95d-11ed-bd46-57d25674f991/tme_frontier_assign-40.log].
log file: /home/wgchen/.ros/log/85118e44-f95d-11ed-bd46-57d25674f991/tme_frontier_assign-40*.log
Initiating shutdown!
================================================================================
[tme_map_compare-41] killing on exit
[tme_frontier_search-39] killing on exit
[tme_frontier_assign-40] killing on exit
[world_to_robot5_tf_broadcaster-38] killing on exit
[world_to_robot4_tf_broadcaster-37] killing on exit
[world_to_robot3_tf_broadcaster-36] killing on exit
[world_to_robot2_tf_broadcaster-35] killing on exit
[world_to_robot1_tf_broadcaster-34] killing on exit
[tme_merger-33] killing on exit
[robot5/robot5_map_tf_broadcaster-32] killing on exit
[robot5/map_extender-31] killing on exit
[robot5/move_base-30] killing on exit

So I want to know that is there something wrong with my configuration or running? or is there a complete tutorial case. thanks!

**Comment by chenweigu** [comment]
Thank you for your reply!
After installing the dependencies according to “install_script.bash“, I put co-explore under the same "catkin_ws/src" and it compiled successfully.

> wgchen@wgchen:~/ws/catkin_ws/src/coExplore-main$ source config_script.bash
> ---------------------------------------------
> coExplore configuration
> ---------------------------------------------
> tme_ROBOT_ENV: [marty, v2_maze, map_3]
> tme_start_num: [2 - 5]
> tme_expl_method: [nearest, minPos, nextFrontier, coExplore, co122]
> tme_stop_time: number in seconds the simluation should run
> ---------------------------------------------
> selected world is: map_3
> starting num of robots 5: [2: True, 3: True, 4: True, 5: True]
> chosen method is: coExplore
> chosen stop time is: 300
> ---------------------------------------------

> wgchen@wgchen:/ws/catkin_ws/src/coExplore-main$ cd ../..
> wgchen@wgchen:/ws/catkin_ws$ source ./devel/setup.bash
> wgchen@wgchen:~/ws/catkin_ws$ roslaunch tme_startup complete_launch.launch

Then some errors appear:

_process[tme_frontier_search-39]: started with pid [7369]
INFO: cannot create a symlink to latest log directory: [Errno 17] File exists: '/home/wgchen/.ros/log/85118e44-f95d-11ed-bd46-57d25674f991' -> '/home/wgchen/.ros/log/latest'
process[tme_frontier_assign-40]: started with pid [7372]
process[tme_map_compare-41]: started with pid [7381]
[ INFO] [1684841559.443016737]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1684841559.443893426]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1684841559.710251326, 10.499000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1684841559.725833965, 10.514000000]: Physics dynamic reconfigure ready.
../src/intel/isl/isl.c:2105: FINISHME: ../src/intel/isl/isl.c:isl_surf_supports_ccs: CCS for 3D textures is disabled, but a workaround is available.
Traceback (most recent call last):
File "/home/wgchen/ws/catkin_ws/devel/lib/tme_exploration/frontier_assign", line 15, in
exec(compile(fh.read(), python_script, 'exec'), context)
File "/home/wgchen/ws/catkin_ws/src/coExplore-main/tme_exploration/src/frontier_assign", line 16, in
from skimage import graph
ModuleNotFoundError: No module named 'skimage'
================================================================================REQUIRED process [tme_frontier_assign-40] has died!
process has died [pid 7372, exit code 1, cmd bash -c sleep 1.0;
@ /home/wgchen/ws/catkin_ws/devel/lib/tme_exploration/frontier_assign __name:=tme_frontier_assign __log:=/home/wgchen/.ros/log/85118e44-f95d-11ed-bd46-57d25674f991/tme_frontier_assign-40.log].
log file: /home/wgchen/.ros/log/85118e44-f95d-11ed-bd46-57d25674f991/tme_frontier_assign-40*.log
Initiating shutdown!

[tme_map_compare-41] killing on exit
[tme_frontier_search-39] killing on exit
[tme_frontier_assign-40] killing on exit
[world_to_robot5_tf_broadcaster-38] killing on exit
[world_to_robot4_tf_broadcaster-37] killing on exit
[world_to_robot3_tf_broadcaster-36] killing on exit
[world_to_robot2_tf_broadcaster-35] killing on exit
[world_to_robot1_tf_broadcaster-34] killing on exit
[tme_merger-33] killing on exit
[robot5/robot5_map_tf_broadcaster-32] killing on exit
[robot5/map_extender-31] killing on exit
[robot5/move_base-30] killing on exit

So I want to know that is there something wrong with my configuration or running? or is there a complete tutorial case. thanks!

**Comment by chenweigu** [comment]
Thank you for your reply!
After installing the dependencies according to “install_script.bash“, I put co-explore under the same "catkin_ws/src" and it compiled successfully.
'''
wgchen@wgchen:~/ws/catkin_ws/src/coExplore-main$ source config_script.bash
wgchen@wgchen:/ws/catkin_ws/src/coExplore-main$ cd ../..
wgchen@wgchen:/ws/catkin_ws$ source ./devel/setup.bash
wgchen@wgchen:~/ws/catkin_ws$ roslaunch tme_startup complete_launch.launch
'''
Then some errors appear:
'''
process[tme_frontier_search-39]: started with pid [7369]
INFO: cannot create a symlink to latest log directory: [Errno 17] File exists: '/home/wgchen/.ros/log/85118e44-f95d-11ed-bd46-57d25674f991' -> '/home/wgchen/.ros/log/latest'
process[tme_frontier_assign-40]: started with pid [7372]
process[tme_map_compare-41]: started with pid [7381]
[ INFO] [1684841559.443016737]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1684841559.443893426]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1684841559.710251326, 10.499000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1684841559.725833965, 10.514000000]: Physics dynamic reconfigure ready.
../src/intel/isl/isl.c:2105: FINISHME: ../src/intel/isl/isl.c:isl_surf_supports_ccs: CCS for 3D textures is disabled, but a workaround is available.
Traceback (most recent call last):
File "/home/wgchen/ws/catkin_ws/devel/lib/tme_exploration/frontier_assign", line 15, in
exec(compile(fh.read(), python_script, 'exec'), context)
File "/home/wgchen/ws/catkin_ws/src/coExplore-main/tme_exploration/src/frontier_assign", line 16, in
from skimage import graph
ModuleNotFoundError: No module named 'skimage'
================================================================================REQUIRED process [tme_frontier_assign-40] has died!
process has died [pid 7372, exit code 1, cmd bash -c sleep 1.0;
@ /home/wgchen/ws/catkin_ws/devel/lib/tme_exploration/frontier_assign __name:=tme_frontier_assign __log:=/home/wgchen/.ros/log/85118e44-f95d-11ed-bd46-57d25674f991/tme_frontier_assign-40.log].
log file: /home/wgchen/.ros/log/85118e44-f95d-11ed-bd46-57d25674f991/tme_frontier_assign-40*.log
Initiating shutdown!

[tme_map_compare-41] killing on exit
[tme_frontier_search-39] killing on exit
[tme_frontier_assign-40] killing on exit
[world_to_robot5_tf_broadcaster-38] killing on exit
[world_to_robot4_tf_broadcaster-37] killing on exit
[world_to_robot3_tf_broadcaster-36] killing on exit
[world_to_robot2_tf_broadcaster-35] killing on exit
[world_to_robot1_tf_broadcaster-34] killing on exit
[tme_merger-33] killing on exit
[robot5/robot5_map_tf_broadcaster-32] killing on exit
[robot5/map_extender-31] killing on exit
[robot5/move_base-30] killing on exit
'''
So I want to know that is there something wrong with my configuration or running? or is there a complete tutorial case. thanks!

**Comment by chenweigu** [comment]
Thank you for your reply!
After installing the dependencies according to “install_script.bash“, I put co-explore under the same "catkin_ws/src" and it compiled successfully.
```
wgchen@wgchen:~/ws/catkin_ws/src/coExplore-main$ source config_script.bash
wgchen@wgchen:/ws/catkin_ws/src/coExplore-main$ cd ../..
wgchen@wgchen:/ws/catkin_ws$ source ./devel/setup.bash
wgchen@wgchen:~/ws/catkin_ws$ roslaunch tme_startup complete_launch.launch
```

Then some errors appear:

```
process[tme_frontier_search-39]: started with pid [7369]
INFO: cannot create a symlink to latest log directory: [Errno 17] File exists: '/home/wgchen/.ros/log/85118e44-f95d-11ed-bd46-57d25674f991' -> '/home/wgchen/.ros/log/latest'
process[tme_frontier_assign-40]: started with pid [7372]
process[tme_map_compare-41]: started with pid [7381]
[ INFO] [1684841559.443016737]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1684841559.443893426]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1684841559.710251326, 10.499000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1684841559.725833965, 10.514000000]: Physics dynamic reconfigure ready.
../src/intel/isl/isl.c:2105: FINISHME: ../src/intel/isl/isl.c:isl_surf_supports_ccs: CCS for 3D textures is disabled, but a workaround is available.
Traceback (most recent call last):
File "/home/wgchen/ws/catkin_ws/devel/lib/tme_exploration/frontier_assign", line 15, in
exec(compile(fh.read(), python_script, 'exec'), context)
File "/home/wgchen/ws/catkin_ws/src/coExplore-main/tme_exploration/src/frontier_assign", line 16, in
from skimage import graph
ModuleNotFoundError: No module named 'skimage'
================================================================================REQUIRED process [tme_frontier_assign-40] has died!
process has died [pid 7372, exit code 1, cmd bash -c sleep 1.0;
@ /home/wgchen/ws/catkin_ws/devel/lib/tme_exploration/frontier_assign __name:=tme_frontier_assign __log:=/home/wgchen/.ros/log/85118e44-f95d-11ed-bd46-57d25674f991/tme_frontier_assign-40.log].
log file: /home/wgchen/.ros/log/85118e44-f95d-11ed-bd46-57d25674f991/tme_frontier_assign-40*.log
Initiating shutdown!

[tme_map_compare-41] killing on exit
[tme_frontier_search-39] killing on exit
[tme_frontier_assign-40] killing on exit
[world_to_robot5_tf_broadcaster-38] killing on exit
[world_to_robot4_tf_broadcaster-37] killing on exit
[world_to_robot3_tf_broadcaster-36] killing on exit
[world_to_robot2_tf_broadcaster-35] killing on exit
[world_to_robot1_tf_broadcaster-34] killing on exit
[tme_merger-33] killing on exit
[robot5/robot5_map_tf_broadcaster-32] killing on exit
[robot5/map_extender-31] killing on exit
[robot5/move_base-30] killing on exit
```

So I want to know that is there something wrong with my configuration or running? or is there a complete tutorial case. thanks!

**Comment by chenweigu** [comment]
> Can you please provide more information about the issue, like the error message, system information, which ROS and os you use for example?
> 
> Then we can more easily pinpoint the problem.

Thank you for your reply!
After installing the dependencies according to “install_script.bash“, I put co-explore under the same "catkin_ws/src" and it compiled successfully.
```
wgchen@wgchen:~/ws/catkin_ws/src/coExplore-main$ source config_script.bash
wgchen@wgchen:/ws/catkin_ws/src/coExplore-main$ cd ../..
wgchen@wgchen:/ws/catkin_ws$ source ./devel/setup.bash
wgchen@wgchen:~/ws/catkin_ws$ roslaunch tme_startup complete_launch.launch
```

Then some errors appear:

```
process[tme_frontier_search-39]: started with pid [7369]
INFO: cannot create a symlink to latest log directory: [Errno 17] File exists: '/home/wgchen/.ros/log/85118e44-f95d-11ed-bd46-57d25674f991' -> '/home/wgchen/.ros/log/latest'
process[tme_frontier_assign-40]: started with pid [7372]
process[tme_map_compare-41]: started with pid [7381]
[ INFO] [1684841559.443016737]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1684841559.443893426]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1684841559.710251326, 10.499000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1684841559.725833965, 10.514000000]: Physics dynamic reconfigure ready.
../src/intel/isl/isl.c:2105: FINISHME: ../src/intel/isl/isl.c:isl_surf_supports_ccs: CCS for 3D textures is disabled, but a workaround is available.
Traceback (most recent call last):
File "/home/wgchen/ws/catkin_ws/devel/lib/tme_exploration/frontier_assign", line 15, in
exec(compile(fh.read(), python_script, 'exec'), context)
File "/home/wgchen/ws/catkin_ws/src/coExplore-main/tme_exploration/src/frontier_assign", line 16, in
from skimage import graph
ModuleNotFoundError: No module named 'skimage'
================================================================================REQUIRED process [tme_frontier_assign-40] has died!
process has died [pid 7372, exit code 1, cmd bash -c sleep 1.0;
@ /home/wgchen/ws/catkin_ws/devel/lib/tme_exploration/frontier_assign __name:=tme_frontier_assign __log:=/home/wgchen/.ros/log/85118e44-f95d-11ed-bd46-57d25674f991/tme_frontier_assign-40.log].
log file: /home/wgchen/.ros/log/85118e44-f95d-11ed-bd46-57d25674f991/tme_frontier_assign-40*.log
Initiating shutdown!

[tme_map_compare-41] killing on exit
[tme_frontier_search-39] killing on exit
[tme_frontier_assign-40] killing on exit
[world_to_robot5_tf_broadcaster-38] killing on exit
[world_to_robot4_tf_broadcaster-37] killing on exit
[world_to_robot3_tf_broadcaster-36] killing on exit
[world_to_robot2_tf_broadcaster-35] killing on exit
[world_to_robot1_tf_broadcaster-34] killing on exit
[tme_merger-33] killing on exit
[robot5/robot5_map_tf_broadcaster-32] killing on exit
[robot5/map_extender-31] killing on exit
[robot5/move_base-30] killing on exit
```

So I want to know that is there something wrong with my configuration or running? or is there a complete tutorial case. thanks!

**Comment by Icheler** [comment]
You posted the same comment quite a few times, I think you only need to install skimage for python with pip. 

I might not have included that in the instructions because I forgot, sorry.

**Comment by chenweigu** [comment]
Sorry, because the terminal outputs too much information, but skimage is not the source of the error.
I want to know if I'm configuring and running the right process, then I can correct the specific errors by myself.

> You posted the same comment quite a few times, I think you only need to install skimage for python with pip.
> 
> I might not have included that in the instructions because I forgot, sorry.

**Comment by Icheler** [comment]
ModuleNotFoundError: No module named 'skimage'

FrontierAssign has to run, if it somehow fails, for example if the input fails, the whole program is shutdown because it is set to be required. I assume the process should be correct, but that is the error that starts the end of it

**Comment by chenweigu** [comment]
> ModuleNotFoundError: No module named 'skimage'
> 
> FrontierAssign has to run, if it somehow fails, for example if the input fails, the whole program is shutdown because it is set to be required. I assume the process should be correct, but that is the error that starts the end of it

I found some files in the co-explore package that contain the directory "TU_Much_Exploration" in the code, and I also found "FileNotFoundError" in the error, how to solve it?
After running "complete_launch.launch", errors appear.
```
Traceback (most recent call last):
  File "/home/wgchen/ws/catkin_ws/devel/lib/tme_exploration/map_compare", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/home/wgchen/ws/catkin_ws/src/coExplore-main/tme_exploration/src/map_compare", line 94, in <module>
    baseLine = np.loadtxt(base_file, ndmin=2)
  File "/home/wgchen/.local/lib/python3.8/site-packages/numpy/lib/npyio.py", line 1356, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
  File "/home/wgchen/.local/lib/python3.8/site-packages/numpy/lib/npyio.py", line 975, in _read
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/home/wgchen/.local/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/home/wgchen/.local/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 533, in open
    raise FileNotFoundError(f"{path} not found.")
FileNotFoundError: /home/wgchen/catkin_ws/src/TU_Much_Exploration/tme_data/coverage/base_line/map_3.txt not found.
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/wgchen/ws/catkin_ws/src/coExplore-main/tme_exploration/src/map_compare", line 56, in exit_handler
    a_file = open(file_complete, "w+")
FileNotFoundError: [Errno 2] No such file or directory: '/home/wgchen/catkin_ws/src/TU_Much_Exploration/tme_data/coverage/measurements/5/map_3_coExplore_2023-05-24-12:15:02.txt'
================================================================================REQUIRED process [tme_map_compare-42] has died!
process has died [pid 28983, exit code 1, cmd bash -c sleep 6.0; $0 $@ /home/wgchen/ws/catkin_ws/devel/lib/tme_exploration/map_compare __name:=tme_map_compare __log:=/home/wgchen/.ros/log/89a4cf84-f9e9-11ed-a254-999c49743777/tme_map_compare-42.log].
log file: /home/wgchen/.ros/log/89a4cf84-f9e9-11ed-a254-999c49743777/tme_map_compare-42*.log
Initiating shutdown!
================================================================================
```

**Comment by Icheler** [comment]
Sorry, apparently I introduced some problems while cleaning up. The project was originally named TU_Much_Exploration, and might have been the last project name on my drive as well, during testing. The quickest fix to this specific issue would be to rename the git folder locally to it. I will be having a look into these problems and testing it with a clean install if I have time in the coming days. I don't promise anything, but I will try to have a look.

**Comment by chenweigu** [comment]
> Sorry, apparently I introduced some problems while cleaning up. The project was originally named TU_Much_Exploration, and might have been the last project name on my drive as well, during testing. The quickest fix to this specific issue would be to rename the git folder locally to it. I will be having a look into these problems and testing it with a clean install if I have time in the coming days. I don't promise anything, but I will try to have a look.

OK! thanks!

**Comment by chenweigu** [comment]
> Sorry, apparently I introduced some problems while cleaning up. The project was originally named TU_Much_Exploration, and might have been the last project name on my drive as well, during testing. The quickest fix to this specific issue would be to rename the git folder locally to it. I will be having a look into these problems and testing it with a clean install if I have time in the coming days. I don't promise anything, but I will try to have a look.

Excuse me, will the author still update?

**Comment by Icheler** [comment]
I am currently busy with more pressing issues. I started to look into it but ran into unconnected TF-Trees after changing the folder name. I am trying to find a solution but have limited time for this project, so this will take a while. I still do not promise anything in terms of progress or timeline.

**Comment by Zheng-CW** [comment]
> 您已完成完整的运行示例吗？配置后，运行启动文件，发现很多参数返回了。
您好，请问这个框架您成功运行了吗？目前我在编译和运行有问题，可以请教您吗？

**Comment by Zheng-CW** [comment]
Hello, I encountered the same problem as you before, how to solve it? I have solved part of the problem, but I can't solve the remaining problems personally. Could you give me some help. Thank you.
![2023-10-30 22-11-00 的屏幕截图](https://github.com/Icheler/coExplore/assets/114415488/821a3741-2283-4788-98af-d51ae5fc85d2)
![2023-10-30 22-11-03 的屏幕截图](https://github.com/Icheler/coExplore/assets/114415488/d229f0c7-ca04-4628-976f-e89a33780500)
![2023-10-30 22-11-06 的屏幕截图](https://github.com/Icheler/coExplore/assets/114415488/4ba03212-1db5-4932-93a8-7850ba1d6643)

**Comment by Icheler** [comment]
This projected is deprecated, some new version of a package broke something. I could not fix it in a reasonable amount of time, so I will not be providing support on these issues.
