### ISSUE TITLE
How to quick start?

### ISSUE THREAD

**Issue by biosbeta** [Icheler/TU_Much_Exploration#2]
How to quick start？Please give a tutorial.

**Comment by Icheler** [comment]
I will have a look in the coming days, and see how easily I can provide a quickstart tutorial. I don't promise anything, but I will have a look.

**Comment by Zheng-CW** [comment]
Hello, I have the some problems, how can I solve it? I have solved part of the problem, but I can't solve the remaining problems personally. Did you encounter the same problem when running the launch file?
Could you give me some help. Thank you for sincerely!
![2023-10-30 22-11-00 的屏幕截图](https://github.com/Icheler/coExplore/assets/114415488/b1ba36bf-7ef4-4abf-80fe-4669b1426218)
![2023-10-30 22-11-03 的屏幕截图](https://github.com/Icheler/coExplore/assets/114415488/a9b562e6-c180-471c-a145-4603867ce250)
![2023-10-30 22-11-06 的屏幕截图](https://github.com/Icheler/coExplore/assets/114415488/daffd2a2-df0e-48d0-9104-e19ec7d576a0)

**Comment by Icheler** [comment]
This projected is deprecated, some new version of a package broke something. I could not fix it in a reasonable amount of time, so I will not be providing support on these issues.
