### ISSUE TITLE
thanks

### ISSUE THREAD

**Issue by mehdikerbelae** [Icheler/TU_Much_Exploration#3]

**Comment by Zheng-CW** [comment]
Hello, I have the some problems, how can I solve it? I have solved part of the problem, but I can't solve the remaining problems personally. Did you encounter the same problem when running the launch file?
Could you give me some help. Thank you for sincerely!
![2023-10-30 22-11-00 的屏幕截图](https://github.com/Icheler/coExplore/assets/114415488/496442d2-755e-4b9f-907c-9bf3ef70b1ef)
![2023-10-30 22-11-03 的屏幕截图](https://github.com/Icheler/coExplore/assets/114415488/16f7c369-30e7-4f82-921b-a9119eb3ada4)
![2023-10-30 22-11-06 的屏幕截图](https://github.com/Icheler/coExplore/assets/114415488/e0869cb3-0d7a-4026-80db-19a8987ce6d5)

**Comment by Icheler** [comment]
This projected is deprecated, some new version of a package broke something. I could not fix it in a reasonable amount of time, so I will not be providing support on these issues.
