### ISSUE TITLE
some problems happen when i run launch files!

### ISSUE THREAD

**Issue by Zheng-CW** [Icheler/TU_Much_Exploration#4]
Excuse me, how to run the launch files?What is the order in which to run the files?
when i run the complete_launch.launch, there are many errors as follows:
![2023-10-30 21-27-19 的屏幕截图](https://github.com/Icheler/coExplore/assets/114415488/4f78071d-8138-46ff-bfb2-7ab47da2d59f)
![2023-10-30 21-27-23 的屏幕截图](https://github.com/Icheler/coExplore/assets/114415488/d10c24d3-9607-46dd-96c2-1ff6afc29a54)
![2023-10-30 21-27-33 的屏幕截图](https://github.com/Icheler/coExplore/assets/114415488/6576b458-542d-4217-ba1e-57a2e3d55a9a)
![2023-10-30 21-27-35 的屏幕截图](https://github.com/Icheler/coExplore/assets/114415488/03c20ed7-57be-4f50-b6b9-dff48610f607)

Could you please tell me how to solve these problems? thank you for sincerely!

**Comment by Zheng-CW** [comment]
sorry it's my fault, I downloaded the wrong version of the "slam_toolbox" package, sorry.

**Comment by Zheng-CW** [comment]
sorry it's my fault, I downloaded the wrong version of the "slam_toolbox" package, sorry.

**Comment by Zheng-CW** [comment]
Hello, I have the same problem as the first person, how can I solve it? I have solved part of the problem, but I can't solve the remaining problems personally. Could you give me some help. Thank you.
![2023-10-30 22-11-00 的屏幕截图](https://github.com/Icheler/coExplore/assets/114415488/02148a5e-1c35-4f8b-9bfb-02e1586ed458)
![2023-10-30 22-11-03 的屏幕截图](https://github.com/Icheler/coExplore/assets/114415488/0c719fee-6536-4172-be47-6d7bc1344623)
![2023-10-30 22-11-06 的屏幕截图](https://github.com/Icheler/coExplore/assets/114415488/dec54f38-0d14-48a7-9a8c-73e7b1d62f70)

**Comment by Icheler** [comment]
This projected is deprecated, some new version of a package broke something. I could not fix it in a reasonable amount of time, so I will not be providing support on these issues.
