### ISSUE TITLE
 Some error issues after running the launch file！

### ISSUE THREAD

**Issue by Zheng-CW** [Icheler/TU_Much_Exploration#5]
Hello author, please allow me to interrupt you for some time, I have encountered some problems after running your open source framework (coExplore), so I ask you to give me some suggestions to solve the problem.
The problems encountered when running the complete_launch.launch file are as follows:
![2023-11-01 11-04-01 的屏幕截图](https://github.com/Icheler/coExplore/assets/114415488/f8050518-2285-4c16-93c7-71bcce7b1c65)

![2023-11-01 11-04-06 的屏幕截图](https://github.com/Icheler/coExplore/assets/114415488/a2a57856-6077-49b3-a586-7eea47a57a68)

![2023-11-01 11-04-09 的屏幕截图](https://github.com/Icheler/coExplore/assets/114415488/7ed20463-0308-4b5c-9ad1-8bf680e1bc00)
The warning is not a big problem, the problem now is the file path, and the package TU_Much_Exploration is not found, so I found that the error after running the complete_launch.launch file is caused by this problem, how can I solve it?
If you can spare time to give me some valuable advice, thank you for sincerely!

**Comment by Icheler** [comment]
This projected is deprecated, some new version of a package broke something. I could not fix it in a reasonable amount of time, so I will not be providing support on these issues.
